name: Terraform Destroy
run-name: Terraform Destroy
on:
  workflow_dispatch
jobs:
  plan_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION: us-east-1

    steps:
      - name: checkout
        uses: actions/checkout@v3 
        
      - name: Get terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init
        
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -var-file="variables.tfvars" -auto-approve

  