name: sample workflow
run-name: ${{ github.event.issue }} sample workflow
on:
  push
jobs:
  display_message:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World!"
      - name: display hostname
        run: hostname
  