name: Terraform Plan and Apply
run-name: Terraform Plan and Apply
on:
  push:
    branches:
      - main
jobs:
  plan_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secerts.AWS_SECRET_ACCESS_KEY }}
      REGION: us-east-1

    steps:
      - name: checkout
        uses: actions/checkout@v3 
        
      - name: Get terraform
        uses: hashicorp/setup-teraform@v1

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="variables.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="variables.tfvars" -auto-approve

  